target_df:
  path: './data/raw/mangalib_full.csv'
  name_cols: ['name', 'eng_name', 'original_name']
  name: 'mangalib'

source_df:
  path: 'data/gmanga_matched_remanga.csv'
  name_cols: ['name', 'original_name', 'eng_name']

result:
  path: 'data/gmanga_matched_remanga_mangalib.csv'
  hist_path: 'pics/gmanga_mangalib_matches.png'