target_df:
  path: './data/raw/remanga_catalog_full.csv'
  name_cols: ['rus_name', 'en_name']
  name: 'remanga'

source_df:
  path: 'data/raw/mint.csv'
  name_cols: ['name', 'original_name', 'eng_name']

result:
  path: 'data/gmint_matched_remanga.csv'
  hist_path: 'pics/gmint_remanga_matches.png'